# ---------------------------------------------------------------------------
# LLM-based distances and similarities
# ---------------------------------------------------------------------------

.extract_llm_score_0_100 <- function(text) {
  text <- paste(text, collapse = "\n")
  matches <- regmatches(text, gregexpr("\\b(?:100|[0-9]{1,2})(?:\\.[0-9]+)?\\b", text, perl = TRUE))[[1]]
  if (length(matches) == 0) return(NA_real_)

  score <- suppressWarnings(as.numeric(utils::tail(matches, 1)))
  if (length(score) != 1 || is.na(score) || score < 0 || score > 100) {
    return(NA_real_)
  }

  score
}

#' LLM text similarity
#'
#' Compute a similarity score, on a scale ranging from 0 (totally different)
#' to 100 (the exact same), between two character strings.
#'
#' @param textA,textB Two character strings.
#' @param model Ollama model name.
#' @param max_attempts Maximum number of attempts used to obtain a valid score.
#' @param ... Additional arguments passed to `ollamar::generate`.
#'
#' @return A numeric score between 0 and 100.
#'
#' @details The similarity score is generated by an LLM. Therefore, the result
#' might vary if the function is run several times.
#'
#' @export
#'
#' @examples
#'\dontrun{
#' textA <- "Participant A was described as a nice, outgoing man, with a friendly attitude."
#' textB <- "Participant A was an extroverted and caring individual."
#' sim_llm(textA, textB)
#' }
sim_llm <- function(textA, textB, model = "llama3", max_attempts = 3, ...) {
  if (!is.character(textA) || length(textA) != 1 || is.na(textA)) {
    stop("`textA` must be a single character string.", call. = FALSE)
  }
  if (!is.character(textB) || length(textB) != 1 || is.na(textB)) {
    stop("`textB` must be a single character string.", call. = FALSE)
  }
  assert_positive_integerish(max_attempts, "max_attempts")

  prompt <- glue::glue(
    "Two experts have each provided a short report. Please identify only the similarities in meaning between the two reports and give a score for the similarity between the two reports: 0 means totally different, 100 means identical.\n\n",
    "# The first report is:\n{textA}\n\n",
    "# The second report is:\n{textB}\n\n",
    "At the very end of your answer, write the score using exactly this format:\n",
    "The similarity between the two reports is: <score>"
  )

  ollama_api_options <- filter_ollama_options(list(...))

  for (attempt in seq_len(max_attempts)) {
    response <- tryCatch({
      res <- .call_ollama_base(
        model = model,
        prompt = prompt,
        output = "df",
        ollama_api_options = ollama_api_options
      )
      paste(res$response, collapse = "\n")
    }, error = function(e) {
      if (attempt == max_attempts) stop(e)
      NA_character_
    })

    if (is.na(response)) next

    score <- .extract_llm_score_0_100(response)
    if (!is.na(score)) return(score)
  }

  stop("The LLM did not return a valid numeric similarity score between 0 and 100.", call. = FALSE)
}

#' LLM distance matrix
#'
#' Compute a distance matrix between randomly-generated responses to an LLM prompt.
#'
#' @param ppt An LLM prompt.
#' @param n The number of responses to be generated.
#' @param per_miss The probability of leaving a pairwise distance missing.
#' @param model Ollama model name.
#' @param max_attempts Maximum number of attempts used to obtain valid similarity scores.
#' @param ... Additional arguments passed to `ollamar::generate`.
#'
#' @return A list containing the generated LLM responses and a distance matrix.
#'
#' @export
#'
#' @examples
#'\dontrun{
#' dist_mat_llm("Explain iris species differences", n = 5, per_miss = 0)
#' }
dist_mat_llm <- function(ppt, n, per_miss = 0, model = "llama3", max_attempts = 3, ...) {
  if (!is.character(ppt) || length(ppt) != 1 || is.na(ppt) || !nzchar(ppt)) {
    stop("`ppt` must be a single non-empty character string.", call. = FALSE)
  }
  assert_positive_integerish(n, "n")
  assert_numeric_scalar(per_miss, "per_miss", lower = 0, upper = 1, inclusive = TRUE)
  assert_positive_integerish(max_attempts, "max_attempts")

  ollama_api_options <- filter_ollama_options(list(...))
  responses <- vector("list", n)

  for (i in seq_len(n)) {
    responses[[i]] <- .call_ollama_base(
      model = model,
      prompt = ppt,
      output = "df",
      ollama_api_options = ollama_api_options
    )
  }

  sim_matrix <- matrix(NA_real_, n, n)
  diag(sim_matrix) <- 100

  for (i in seq_len(n)) {
    if (i <= 1) next
    for (j in seq_len(i - 1)) {
      if (stats::runif(1) > per_miss) {
        sim_matrix[i, j] <- sim_llm(
          paste(responses[[i]]$response, collapse = "\n"),
          paste(responses[[j]]$response, collapse = "\n"),
          model = model,
          max_attempts = max_attempts,
          ...
        )
        sim_matrix[j, i] <- sim_matrix[i, j]
      }
    }
  }

  list(boot_llm = responses, dist_llm = 100 - sim_matrix)
}

#' LLM response consistency
#'
#' Compute distances between an LLM response of interest and new responses to
#' the same prompt.
#'
#' @param ppt An LLM prompt.
#' @param ref The reference response.
#' @param n The number of new responses to be generated.
#' @param model Ollama model name.
#' @param max_attempts Maximum number of attempts used to obtain valid similarity scores.
#' @param ... Additional arguments passed to `ollamar::generate`.
#'
#' @return A list containing generated responses and distances to the reference.
#'
#' @export
#'
#' @examples
#'\dontrun{
#' dist_ref_llm("Explain iris species differences", "Reference response", n = 5)
#' }
dist_ref_llm <- function(ppt, ref, n, model = "llama3", max_attempts = 3, ...) {
  if (!is.character(ppt) || length(ppt) != 1 || is.na(ppt) || !nzchar(ppt)) {
    stop("`ppt` must be a single non-empty character string.", call. = FALSE)
  }
  if (!is.character(ref) || length(ref) != 1 || is.na(ref)) {
    stop("`ref` must be a single character string.", call. = FALSE)
  }
  assert_positive_integerish(n, "n")
  assert_positive_integerish(max_attempts, "max_attempts")

  ollama_api_options <- filter_ollama_options(list(...))
  responses <- vector("list", n)

  for (i in seq_len(n)) {
    responses[[i]] <- .call_ollama_base(
      model = model,
      prompt = ppt,
      output = "df",
      ollama_api_options = ollama_api_options
    )
  }

  distance_matrix <- matrix(NA_real_, n, 1)
  for (i in seq_len(n)) {
    distance_matrix[i, 1] <- 100 - sim_llm(
      ref,
      paste(responses[[i]]$response, collapse = "\n"),
      model = model,
      max_attempts = max_attempts,
      ...
    )
  }

  list(boot_llm = responses, dist_llm = distance_matrix)
}
