#' @importFrom dplyr filter arrange desc
#' @importFrom glue glue
#' @importFrom knitr kable
#' @importFrom utils globalVariables
#' @importFrom FactoMineR PCA

utils::globalVariables(c(".data", "coord", "abs_coord", "correlation", "abs_correlation"))

# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

validate_qda_space_inputs <- function(ncp, scale.unit, min_inertia_pct,
                                      top_n_var, top_n_products, generate,
                                      expertise_mode) {
  if (!is.numeric(ncp) || length(ncp) != 1 || is.na(ncp) || ncp < 1) {
    stop("`ncp` must be a single numeric value >= 1.", call. = FALSE)
  }

  if (!is.logical(scale.unit) || length(scale.unit) != 1 || is.na(scale.unit)) {
    stop("`scale.unit` must be a single non-missing logical value.", call. = FALSE)
  }

  if (!is.numeric(min_inertia_pct) || length(min_inertia_pct) != 1 || is.na(min_inertia_pct) ||
      min_inertia_pct < 0 || min_inertia_pct > 100) {
    stop("`min_inertia_pct` must be a single numeric value in [0, 100].", call. = FALSE)
  }

  if (!is.numeric(top_n_var) || length(top_n_var) != 1 || is.na(top_n_var) || top_n_var < 1) {
    stop("`top_n_var` must be a single numeric value >= 1.", call. = FALSE)
  }

  if (!is.numeric(top_n_products) || length(top_n_products) != 1 || is.na(top_n_products) || top_n_products < 1) {
    stop("`top_n_products` must be a single numeric value >= 1.", call. = FALSE)
  }

  if (!is.logical(generate) || length(generate) != 1 || is.na(generate)) {
    stop("`generate` must be a single non-missing logical value.", call. = FALSE)
  }

  if (!expertise_mode %in% c("sensory", "positioning", "hybrid")) {
    stop("`expertise_mode` must be one of: 'sensory', 'positioning', 'hybrid'.", call. = FALSE)
  }

  invisible(TRUE)
}

# ---------------------------------------------------------------------------
# Extract inputs from nail_qda outputs or raw decat results
# ---------------------------------------------------------------------------

.extract_qda_space_inputs <- function(x, profile_summary = NULL) {
  decat_result <- attr(x, "decat_result", exact = TRUE)
  profile_attr <- attr(x, "profile_summary", exact = TRUE)

  if (!is.null(decat_result)) {
    if (is.null(profile_summary)) {
      profile_summary <- profile_attr
    }
    return(list(
      decat_result = decat_result,
      profile_summary = profile_summary
    ))
  }

  if (is.list(x) && !is.null(x$adjmean)) {
    return(list(
      decat_result = x,
      profile_summary = profile_summary
    ))
  }

  stop("`x` must be either an object returned by `nail_qda()` or a raw `decat` result containing `adjmean`.", call. = FALSE)
}

.extract_llm_profile_summaries <- function(llm_product_summaries) {
  if (is.null(llm_product_summaries)) {
    return(NULL)
  }

  out <- list()

  for (nm in names(llm_product_summaries)) {
    item <- llm_product_summaries[[nm]]

    parsed <- NULL

    # Standard output from nail_qda_spaceprep(generate = TRUE)
    if (is.list(item) && !is.null(item$parsed)) {
      parsed <- item$parsed
    } else if (is.list(item)) {
      # Also accept an already parsed summary supplied directly.
      has_new_names <- all(c(
        "core_profile",
        "above_average_traits",
        "below_average_traits",
        "positioning_cues",
        "profile_clarity",
        "injectable_summary"
      ) %in% names(item))

      has_legacy_names <- all(c(
        "core_profile",
        "positive_traits",
        "negative_traits",
        "positioning_cues",
        "profile_clarity",
        "injectable_summary"
      ) %in% names(item))

      if (has_new_names || has_legacy_names) {
        parsed <- item
      }
    }

    if (is.null(parsed)) {
      next
    }

    # New canonical names.
    above_traits <- parsed$above_average_traits
    below_traits <- parsed$below_average_traits

    # Backward compatibility with summaries generated by older versions.
    if (is.null(above_traits)) {
      above_traits <- parsed$positive_traits
    }

    if (is.null(below_traits)) {
      below_traits <- parsed$negative_traits
    }

    # Ensure stable empty-vector values when a field is absent.
    if (is.null(above_traits)) {
      above_traits <- character(0)
    }

    if (is.null(below_traits)) {
      below_traits <- character(0)
    }

    out[[nm]] <- list(
      injectable_summary = parsed$injectable_summary,
      positioning_cues = parsed$positioning_cues,
      profile_clarity = parsed$profile_clarity,
      core_profile = parsed$core_profile,
      above_average_traits = above_traits,
      below_average_traits = below_traits
    )
  }

  out
}

# ---------------------------------------------------------------------------
# Prompt builders
# ---------------------------------------------------------------------------

build_guide_qda_space <- function(min_inertia_pct = 10,
                                  expertise_mode = c("sensory", "positioning", "hybrid")) {
  expertise_mode <- match.arg(expertise_mode)
  mode_lines <- switch(
    expertise_mode,
    sensory = c(
      "Interpretation mode: sensory.",
      "Prioritize sensory oppositions between products.",
      "Describe the axes using sensory and perceptual contrasts first."
    ),
    positioning = c(
      "Interpretation mode: positioning.",
      "You may interpret the axes as broader product styles or product poles.",
      "Stay grounded in the sensory evidence."
    ),
    hybrid = c(
      "Interpretation mode: hybrid.",
      "Start from the sensory oppositions and, when relevant, infer broader product styles.",
      "Keep the sensory evidence primary."
    )
  )

  paste(
    c(
      "## How to Read the Results",
      "The product space is built from the adjusted mean sensory profiles of the products.",
      "Each retained dimension summarizes one major opposition in the sensory space, under the current PCA settings.",
      "The sign of a PCA dimension is arbitrary: interpret the opposition between the two ends, not the absolute meaning of positive versus negative coordinates.",
      paste0("Only dimensions explaining at least ", min_inertia_pct, "% of the inertia are interpreted automatically."),
      "",
      "### Variable-level evidence",
      "This section lists the attributes most positively and most negatively associated with the dimension.",
      "These attributes help identify the main sensory opposition carried by the axis, but they should be interpreted as the strongest associations under the current analysis settings.",
      "",
      "### Product-level evidence",
      "This section lists the products located at the negative and positive ends of the dimension.",
      "For each product, the summary recalls the profile of the product in a form meant to help interpret the product space.",
      "",
      mode_lines,
      "",
      "Use both sections together: the variable-level evidence gives the general meaning of the dimension, and the product-level evidence shows how this dimension is expressed in concrete products.",
      "When variable-level evidence and product-level evidence do not align perfectly, prioritize the variable-level structure and use the products as illustrations."
    ),
    collapse = "\n"
  )
}

build_request_qda_space <- function(expertise_mode = c("sensory", "positioning", "hybrid")) {
  expertise_mode <- match.arg(expertise_mode)

  if (expertise_mode == "sensory") {
    return(paste(
      "Using only the results below, interpret each retained dimension of the product sensory space.",
      "For each dimension, explain what sensory opposition structures the axis.",
      "Use the variable-level evidence to identify the general sensory meaning of the dimension.",
      "Use the product-level evidence to explain how this sensory opposition is expressed by the products located at the two ends.",
      "Stay close to sensory and perceptual vocabulary.",
      "If the evidence is partial, mixed, or somewhat unstable, say so explicitly.",
      "Do not interpret the retained attributes as absolute truths; treat them as the strongest associations selected under the current analysis settings.",
      sep = "\n"
    ))
  }

  if (expertise_mode == "positioning") {
    return(paste(
      "Using only the results below, interpret each retained dimension of the product space.",
      "For each dimension, explain what broader product opposition or product style structures the axis.",
      "Use the sensory evidence as the basis of your interpretation.",
      "Use the product-level evidence to explain how the products at the two ends embody this opposition.",
      "If the evidence is partial, mixed, or somewhat unstable, say so explicitly.",
      "Do not interpret the retained attributes as absolute truths; treat them as the strongest associations selected under the current analysis settings.",
      sep = "\n"
    ))
  }

  paste(
    "Using only the results below, interpret each retained dimension of the product space.",
    "For each dimension, first explain the main sensory opposition that structures the axis, then explain what broader product contrast or style it may suggest.",
    "Use the variable-level evidence to identify the sensory structure of the dimension.",
    "Use the product-level evidence to explain how this opposition is expressed by the products located at the two ends.",
    "Keep the sensory evidence primary and the broader interpretation secondary.",
    "If the evidence is partial, mixed, or somewhat unstable, say so explicitly.",
    "Do not interpret the retained attributes as absolute truths; treat them as the strongest associations selected under the current analysis settings.",
    sep = "\n"
  )
}

build_conclusion_qda_space <- function(expertise_mode = c("sensory", "positioning", "hybrid")) {
  expertise_mode <- match.arg(expertise_mode)

  if (expertise_mode == "sensory") {
    return(paste(
      "# Final Summary Task",
      "For each retained dimension, provide:",
      "1. **The main sensory opposition carried by the axis**.",
      "2. **What characterizes the negative end and the positive end in sensory terms**.",
      "3. **How the extreme products help make this opposition concrete**.",
      "",
      "# Output format",
      "Your output must be **formatted using valid Quarto Markdown**.",
      sep = "\n"
    ))
  }

  if (expertise_mode == "positioning") {
    return(paste(
      "# Final Summary Task",
      "For each retained dimension, provide:",
      "1. **The main product opposition or product style contrast carried by the axis**.",
      "2. **What characterizes the negative end and the positive end**.",
      "3. **How the extreme products help make this opposition concrete**.",
      "",
      "# Output format",
      "Your output must be **formatted using valid Quarto Markdown**.",
      sep = "\n"
    ))
  }

  paste(
    "# Final Summary Task",
    "For each retained dimension, provide:",
    "1. **The main sensory opposition carried by the axis**.",
    "2. **The broader product contrast or style that this opposition may suggest**.",
    "3. **What characterizes the negative end and the positive end**.",
    "4. **How the extreme products help make this opposition concrete**.",
    "",
    "# Output format",
    "Your output must be **formatted using valid Quarto Markdown**.",
    sep = "\n"
  )
}

# ---------------------------------------------------------------------------
# Core computations
# ---------------------------------------------------------------------------

.build_qda_space_object <- function(decat_result, ncp = 2, scale.unit = TRUE, min_inertia_pct = 10) {
  adjmean <- as.data.frame(decat_result$adjmean)

  if (nrow(adjmean) < 2 || ncol(adjmean) < 2) {
    stop("`adjmean` must contain at least 2 products and 2 attributes to build a product space.", call. = FALSE)
  }

  max_ncp <- min(ncp, nrow(adjmean) - 1, ncol(adjmean))
  if (max_ncp < 1) {
    stop("No interpretable PCA dimension can be computed from `adjmean`.", call. = FALSE)
  }

  res_pca <- FactoMineR::PCA(
    adjmean,
    scale.unit = scale.unit,
    ncp = max_ncp,
    graph = FALSE
  )

  eig <- as.data.frame(res_pca$eig)
  colnames(eig)[1:3] <- c("eigenvalue", "percent", "cumulative_percent")

  available_axes <- ncol(res_pca$var$cor)

  retained_axes <- which(eig$percent >= min_inertia_pct)
  retained_axes <- retained_axes[retained_axes <= available_axes]

  list(
    pca_result = res_pca,
    adjmean = adjmean,
    eig = eig,
    retained_axes = retained_axes,
    scale.unit = scale.unit,
    min_inertia_pct = min_inertia_pct
  )
}

# ---------------------------------------------------------------------------
# Axis-level evidence
# ---------------------------------------------------------------------------

get_sentences_qda_axis <- function(space_obj, axis, top_n_var = 5) {
  var_cor <- as.data.frame(space_obj$pca_result$var$cor)
  axis_name <- paste0("Dim.", axis)

  if (!axis_name %in% colnames(var_cor)) {
    stop(sprintf("Axis '%s' not found in PCA variable correlations.", axis_name), call. = FALSE)
  }

  axis_df <- data.frame(
    Variable = rownames(var_cor),
    correlation = var_cor[[axis_name]],
    stringsAsFactors = FALSE
  )

  axis_df$abs_correlation <- abs(axis_df$correlation)

  pos_df <- axis_df |>
    dplyr::filter(.data$correlation > 0) |>
    dplyr::arrange(dplyr::desc(.data$abs_correlation))

  neg_df <- axis_df |>
    dplyr::filter(.data$correlation < 0) |>
    dplyr::arrange(dplyr::desc(.data$abs_correlation))

  pos_df <- utils::head(pos_df[, c("Variable", "correlation"), drop = FALSE], top_n_var)
  neg_df <- utils::head(neg_df[, c("Variable", "correlation"), drop = FALSE], top_n_var)

  pos_txt <- if (nrow(pos_df) > 0) {
    paste(
      "### Attributes positively associated with the dimension",
      "",
      paste(knitr::kable(pos_df, digits = 2, format = "pipe", align = c("l", "r")), collapse = "\n"),
      sep = "\n"
    )
  } else {
    "### Attributes positively associated with the dimension\n\n*No positive associations retained.*"
  }

  neg_txt <- if (nrow(neg_df) > 0) {
    paste(
      "### Attributes negatively associated with the dimension",
      "",
      paste(knitr::kable(neg_df, digits = 2, format = "pipe", align = c("l", "r")), collapse = "\n"),
      sep = "\n"
    )
  } else {
    "### Attributes negatively associated with the dimension\n\n*No negative associations retained.*"
  }

  normalize_blank_lines(paste(pos_txt, neg_txt, sep = "\n\n"))
}

# ---------------------------------------------------------------------------
# Product-level evidence
# ---------------------------------------------------------------------------

.build_axis_product_evidence <- function(space_obj, axis,
                                         profile_summary = NULL,
                                         llm_profile_summaries = NULL,
                                         top_n_products = 2) {
  coord_df <- as.data.frame(space_obj$pca_result$ind$coord)
  axis_name <- paste0("Dim.", axis)

  if (!axis_name %in% colnames(coord_df)) {
    stop(sprintf("Axis '%s' not found in PCA individual coordinates.", axis_name), call. = FALSE)
  }

  prod_df <- data.frame(
    Product = rownames(coord_df),
    coord = coord_df[[axis_name]],
    stringsAsFactors = FALSE
  )

  neg_products <- prod_df |>
    dplyr::filter(.data$coord < 0) |>
    dplyr::arrange(.data$coord)

  pos_products <- prod_df |>
    dplyr::filter(.data$coord > 0) |>
    dplyr::arrange(dplyr::desc(.data$coord))

  neg_products <- utils::head(neg_products, top_n_products)
  pos_products <- utils::head(pos_products, top_n_products)

  .one_line_mechanical <- function(product_name, coord_value, profile_summary_item) {
    if (is.null(profile_summary_item)) {
      return(paste0("- ", product_name, " (coord. = ", round(coord_value, 2), ")"))
    }

    above_txt <- if (length(profile_summary_item$above) > 0) {
      paste(profile_summary_item$above, collapse = ", ")
    } else {
      "none"
    }

    below_txt <- if (length(profile_summary_item$below) > 0) {
      paste(profile_summary_item$below, collapse = ", ")
    } else {
      "none"
    }

    paste0(
      "- ", product_name,
      " (coord. = ", round(coord_value, 2), "): ",
      "above average on ", above_txt,
      "; below average on ", below_txt,
      " (profile strength: ", profile_summary_item$profile_strength, ")"
    )
  }

  .one_line_llm <- function(product_name, coord_value, llm_item, fallback_item = NULL) {
    if (is.null(llm_item)) {
      return(.one_line_mechanical(product_name, coord_value, fallback_item))
    }

    summary_txt <- llm_item$injectable_summary
    cue_txt <- llm_item$positioning_cues
    clarity_txt <- llm_item$profile_clarity

    if (is.null(summary_txt) || is.na(summary_txt) || !nzchar(trimws(summary_txt))) {
      return(.one_line_mechanical(product_name, coord_value, fallback_item))
    }

    pieces <- c(
      paste0("- ", product_name, " (coord. = ", round(coord_value, 2), "): ", summary_txt),
      if (!is.null(cue_txt) && !is.na(cue_txt) && nzchar(trimws(cue_txt)))
        paste0(" Intermediate summary cue: ", cue_txt) else NULL,
      if (!is.null(clarity_txt) && !is.na(clarity_txt) && nzchar(trimws(clarity_txt)))
        paste0(" Profile clarity: ", clarity_txt, ".") else NULL
    )

    paste0(pieces, collapse = "")
  }

  neg_lines <- if (nrow(neg_products) > 0) {
    vapply(
      seq_len(nrow(neg_products)),
      function(i) {
        p <- neg_products$Product[i]
        llm_item <- if (!is.null(llm_profile_summaries)) llm_profile_summaries[[p]] else NULL
        fallback_item <- if (!is.null(profile_summary)) profile_summary[[p]] else NULL
        .one_line_llm(p, neg_products$coord[i], llm_item, fallback_item)
      },
      character(1)
    )
  } else {
    "*No product clearly located at the negative end.*"
  }

  pos_lines <- if (nrow(pos_products) > 0) {
    vapply(
      seq_len(nrow(pos_products)),
      function(i) {
        p <- pos_products$Product[i]
        llm_item <- if (!is.null(llm_profile_summaries)) llm_profile_summaries[[p]] else NULL
        fallback_item <- if (!is.null(profile_summary)) profile_summary[[p]] else NULL
        .one_line_llm(p, pos_products$coord[i], llm_item, fallback_item)
      },
      character(1)
    )
  } else {
    "*No product clearly located at the positive end.*"
  }

  paste(
    "### Products at the negative end of the dimension",
    "",
    paste(neg_lines, collapse = "\n"),
    "",
    "### Products at the positive end of the dimension",
    "",
    paste(pos_lines, collapse = "\n"),
    sep = "\n"
  )
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

#' Interpret a product sensory space built from QDA adjusted means
#'
#' Builds a principal component analysis of the adjusted product means
#' obtained from `SensoMineR::decat()`, identifies the main sensory
#' oppositions structuring the product space, and prepares one interpretation
#' prompt for each retained PCA dimension.
#'
#' The function combines two complementary sources of evidence:
#'
#' - sensory attributes that are positively or negatively associated with
#'   each PCA dimension;
#' - products located at the negative and positive ends of each dimension.
#'
#' When `x` is an object returned by `nail_qda()`, deterministic product
#' summaries are extracted automatically and used to make the extreme
#' products more concrete. These summaries do not affect the PCA.
#'
#' Product-level evidence may optionally be enriched with structured LLM
#' summaries produced by `nail_qda_spaceprep(generate = TRUE)`.
#'
#' By default, no language model is called. The function returns the prompts
#' and the complete product-space object so that the statistical structure can
#' be inspected before generation.
#'
#' @param x An object providing the result of the QDA product
#'   characterization.
#'
#'   `x` may be:
#'
#'   - an object returned by `nail_qda()`. This is the recommended workflow.
#'     The function then extracts the `"decat_result"` and
#'     `"profile_summary"` attributes automatically;
#'   - a raw result returned by `SensoMineR::decat()` containing an `adjmean`
#'     component.
#'
#'   The `adjmean` component must contain products in rows and quantitative
#'   sensory attributes in columns.
#' @param profile_summary Optional advanced argument containing deterministic
#'   product-level summaries.
#'
#'   Most users should leave this argument as `NULL`.
#'
#'   When `x` is returned by `nail_qda()`, the `"profile_summary"` attribute
#'   is extracted automatically. Supplying `profile_summary` explicitly
#'   overrides the automatically extracted value.
#'
#'   This argument is mainly useful when `x` is a raw
#'   `SensoMineR::decat()` result and compatible product summaries are
#'   available separately.
#'
#'   Each named element may contain:
#'
#'   - `above`: sensory attributes above the average product profile;
#'   - `below`: sensory attributes below the average product profile;
#'   - `profile_strength`: an indication of how clearly the product differs
#'     from the average profile.
#'
#'   These summaries are used only to enrich the textual description of
#'   products located at the ends of the PCA dimensions. They do not affect
#'   the adjusted mean table, the PCA, the eigenvalues, the product
#'   coordinates, or the retained dimensions.
#' @param llm_product_summaries An optional named list of structured product
#'   summaries, typically returned by
#'   `nail_qda_spaceprep(generate = TRUE)`.
#'
#'   Product names must correspond to the row names of the adjusted mean
#'   table.
#'
#'   When a valid LLM summary is available for a product, its
#'   `injectable_summary`, `positioning_cues`, and `profile_clarity` fields
#'   are included in the product-level evidence.
#'
#'   When no usable LLM summary is available for a product, the function falls
#'   back to the corresponding deterministic summary extracted from
#'   `nail_qda()`, when available.
#'
#'   Results from `nail_qda_spaceprep(generate = FALSE)` contain prompts only
#'   and therefore do not provide parsed product summaries suitable for this
#'   argument.
#'
#'   These summaries affect only the prompt. They do not modify the PCA.
#' @param ncp A single integer greater than or equal to 1 giving the requested
#'   number of PCA dimensions to compute. The default is `2`.
#'
#'   The effective number of dimensions is automatically limited by the
#'   number of products and sensory attributes. It cannot exceed the smallest
#'   of:
#'
#'   - the requested value;
#'   - the number of products minus one;
#'   - the number of sensory attributes.
#'
#'   Computing a dimension does not necessarily mean that it will be
#'   interpreted. Automatic interpretation is also controlled by
#'   `min_inertia_pct`.
#' @param scale.unit Logical indicating whether the sensory attributes should
#'   be standardized to unit variance before PCA. The default is `TRUE`.
#'
#'   With `scale.unit = TRUE`, each sensory attribute is standardized to unit
#'   variance before PCA. This gives the attributes comparable weights in the
#'   construction of the product space and prevents attributes with greater
#'   dispersion from dominating the analysis solely because of their
#'   variability.
#'
#'   This setting is generally appropriate when the objective is to give each
#'   sensory attribute an equivalent role in the analysis.
#'
#'   With `scale.unit = FALSE`, the adjusted mean variables are centered but
#'   their original variances are retained. Attributes with greater variation
#'   across products may therefore contribute more strongly to the product
#'   space.
#'
#'   This alternative may be appropriate when all attributes were measured on
#'   comparable scales and their differences in dispersion are considered
#'   substantively meaningful.
#'
#'   Changing this argument changes the PCA itself and may therefore alter the
#'   dimensions, eigenvalues, product coordinates, and resulting
#'   interpretations.
#' @param min_inertia_pct A numeric value between 0 and 100 giving the minimum
#'   percentage of inertia that a PCA dimension must explain to be interpreted
#'   automatically. The default is `10`.
#'
#'   For example, with `ncp = 4` and `min_inertia_pct = 10`, up to four
#'   dimensions are computed, but prompts are produced only for dimensions
#'   that individually explain at least 10 percent of the total inertia.
#'
#'   This threshold is applied to each dimension separately, not to the
#'   cumulative percentage of inertia.
#' @param top_n_var A single integer greater than or equal to 1 giving the
#'   maximum number of sensory attributes displayed on each side of a
#'   dimension. The default is `5`.
#'
#'   The attributes are ranked by the absolute value of their correlation with
#'   the PCA dimension. Up to `top_n_var` positively associated attributes and
#'   up to `top_n_var` negatively associated attributes are retained.
#'
#'   Consequently, as many as `2 * top_n_var` attributes may be displayed for
#'   one dimension.
#' @param top_n_products A single integer greater than or equal to 1 giving the
#'   maximum number of products displayed at each end of a PCA dimension. The
#'   default is `2`.
#'
#'   Products are ranked using their coordinates on the current dimension.
#'   Up to `top_n_products` products with the most negative coordinates and up
#'   to `top_n_products` products with the most positive coordinates are
#'   retained.
#'
#'   Consequently, as many as `2 * top_n_products` products may be displayed
#'   for one dimension.
#' @param expertise_mode Character string controlling the interpretive
#'   perspective used in the prompt. One of `"sensory"`, `"positioning"`, or
#'   `"hybrid"`.
#'
#'   With `"sensory"`, the interpretation focuses on sensory and perceptual
#'   oppositions. Axis descriptions should remain closely anchored in the
#'   sensory attributes.
#'
#'   With `"positioning"`, the interpretation may extend from the sensory
#'   evidence to broader product styles, product poles, or forms of
#'   positioning.
#'
#'   With `"hybrid"`, the interpretation first identifies the sensory
#'   opposition and may then propose a broader product contrast while keeping
#'   the sensory evidence primary.
#'
#'   This argument changes only the prompt instructions. It does not change
#'   the adjusted mean table or the PCA.
#' @param introduction An optional character string providing the study
#'   context for the interpretation prompt.
#'
#'   A useful introduction may explain:
#'
#'   - which products were evaluated;
#'   - which sensory panel or assessment procedure was used;
#'   - what the sensory attributes represent;
#'   - the purpose of the product-space analysis.
#'
#'   If `NULL`, a default introduction is created according to
#'   `expertise_mode`.
#' @param request An optional character string specifying the interpretation
#'   requested from the language model.
#'
#'   If `NULL`, a default request is created according to `expertise_mode`.
#'   The default request asks the model to interpret each retained dimension
#'   from the sensory attributes and the products located at its two ends.
#' @param conclusion An optional character string defining the expected final
#'   synthesis and output format.
#'
#'   If `NULL`, a default conclusion is created according to
#'   `expertise_mode`. The default asks for a structured interpretation of the
#'   main opposition, the two ends of the dimension, and the products that
#'   illustrate them.
#' @param model Character string giving the language model used by the selected
#'   provider. The default is `"llama3"`, intended for the default Ollama
#'   backend.
#' @param provider LLM backend used when `generate = TRUE`. One of
#'   `"ollama"` or `"gemini"`.
#'
#'   The default is `"ollama"`, which uses a local Ollama installation.
#'
#'   Gemini requires a valid API key, typically supplied through the
#'   `GEMINI_API_KEY` environment variable.
#' @param generate Logical.
#'
#'   If `FALSE`, no language model is called and the function returns one
#'   prompt per retained dimension.
#'
#'   If `TRUE`, each prompt is sent separately to the selected LLM backend and
#'   the function returns one generated result per retained dimension.
#' @param ... Additional provider-specific generation arguments passed to the
#'   selected LLM backend, such as `temperature`, `seed`, or other supported
#'   options.
#'
#' @details
#' ## Construction of the product space
#'
#' The function extracts the adjusted mean table from:
#'
#' ```
#' decat_result$adjmean
#' ```
#'
#' This table has:
#'
#' - products or stimuli in rows;
#' - sensory attributes in columns;
#' - adjusted sensory means in the cells.
#'
#' The adjusted means are estimates obtained from the ANOVA models fitted by
#' `SensoMineR::decat()`. They account for the factors included in the QDA
#' model, such as panelist effects.
#'
#' A PCA is then computed with `FactoMineR::PCA()`. In this PCA:
#'
#' - products are the individuals;
#' - sensory attributes are the quantitative variables;
#' - PCA dimensions summarize the main sensory oppositions between products.
#'
#' The result is a multidimensional product space in which products with
#' similar adjusted sensory profiles tend to be positioned close to one
#' another.
#'
#' The PCA is computed exclusively from the adjusted mean table. Neither
#' `profile_summary` nor `llm_product_summaries` contributes to the statistical
#' construction of the product space.
#'
#' ## Selection of interpreted dimensions
#'
#' The function first computes up to `ncp` dimensions. It then retains only
#' those dimensions whose individual percentage of inertia is greater than or
#' equal to `min_inertia_pct`.
#'
#' A separate prompt is created for each retained dimension.
#'
#' A dimension explaining less than `min_inertia_pct` is still present in the
#' PCA object when it was computed, but it is not interpreted automatically.
#'
#' When no computed dimension reaches the threshold, no LLM call is made. With
#' `generate = FALSE`, the function returns an informative character message
#' with the complete product-space object stored in the `"qda_space"`
#' attribute.
#'
#' ## Variable-level evidence
#'
#' For each retained dimension, the function extracts the correlations between
#' the sensory attributes and that dimension.
#'
#' The attributes with the strongest positive correlations describe one side
#' of the sensory opposition. The attributes with the strongest negative
#' correlations describe the opposite side.
#'
#' The sign of a PCA axis is arbitrary. Reversing all signs would produce an
#' equivalent PCA solution. The interpretation must therefore focus on the
#' contrast between the two ends of the dimension rather than assigning an
#' intrinsic meaning to the positive or negative side.
#'
#' For example, an axis opposing sweetness and milkiness to bitterness and
#' cocoa intensity should be interpreted as this sensory contrast, regardless
#' of which group of attributes appears on the positive side.
#'
#' The number of attributes displayed is controlled by `top_n_var`.
#'
#' ## Product-level evidence
#'
#' The function also identifies the products with the most negative and most
#' positive coordinates on each retained dimension.
#'
#' These extreme products provide concrete illustrations of the sensory
#' opposition identified from the variable correlations.
#'
#' The number of products displayed at each end is controlled by
#' `top_n_products`.
#'
#' Product-level evidence should be interpreted together with the
#' variable-level evidence. When both sources do not align perfectly, the
#' variable correlations define the main structure of the dimension and the
#' products should be treated as illustrations rather than as the sole basis
#' for naming the axis.
#'
#' ## Deterministic product summaries
#'
#' When `x` comes from `nail_qda()`, the function automatically retrieves the
#' `"profile_summary"` attribute.
#'
#' These summaries are compact reformulations of the product-specific QDA
#' results. For an extreme product, they may indicate:
#'
#' - sensory attributes above the average product profile;
#' - sensory attributes below the average product profile;
#' - an indication of the clarity or strength of the product profile.
#'
#' Their purpose is to transform a purely geometric statement such as:
#'
#' ```
#' Product A is located at the negative end of Dimension 1.
#' ```
#'
#' into a more concrete sensory description such as:
#'
#' ```
#' Product A is located at the negative end and is characterized by more
#' bitterness and cocoa intensity and less sweetness and milk flavor than the
#' average product profile.
#' ```
#'
#' These summaries do not provide a new statistical analysis. They reorganize
#' information already produced by `nail_qda()` and are used only to enrich
#' the product-level section of the prompt.
#'
#' Users following the recommended workflow do not need to extract, inspect,
#' or supply `profile_summary` manually.
#'
#' When `x` is a raw `decat()` result and no `profile_summary` is supplied,
#' the products can still be located and interpreted from their PCA
#' coordinates, but their product-specific sensory summaries are not added.
#'
#' ## Optional LLM product summaries
#'
#' `nail_qda_spaceprep()` may be used before `nail_qda_space()` to generate
#' short structured interpretations of the individual product profiles.
#'
#' These summaries are optional. They are not required to compute the PCA or
#' to interpret the product-space dimensions.
#'
#' When supplied through `llm_product_summaries`, they may add:
#'
#' - a short product profile;
#' - a positioning cue;
#' - an indication of profile clarity;
#' - a reusable summary sentence.
#'
#' For a given product, the LLM summary is used when it contains a valid
#' `injectable_summary`. Otherwise, the function falls back to the
#' deterministic summary extracted from `nail_qda()`, when available.
#'
#' The simpler and recommended initial workflow is:
#'
#' ```
#' qda_result <- nail_qda(...)
#' space_prompts <- nail_qda_space(x = qda_result)
#' ```
#'
#' An optional enriched workflow is:
#'
#' ```
#' qda_result <- nail_qda(...)
#'
#' product_summaries <- nail_qda_spaceprep(
#'   ...,
#'   generate = TRUE
#' )
#'
#' space_prompts <- nail_qda_space(
#'   x = qda_result,
#'   llm_product_summaries = product_summaries
#' )
#' ```
#'
#' ## Expertise modes
#'
#' The same PCA evidence can be presented from three interpretive
#' perspectives.
#'
#' In `"sensory"` mode, axis interpretations should remain close to the
#' sensory attributes and perceptual contrasts.
#'
#' In `"positioning"` mode, broader product styles may be inferred, but they
#' must remain grounded in the sensory evidence.
#'
#' In `"hybrid"` mode, the interpretation should first establish the sensory
#' contrast and only then consider a broader product meaning.
#'
#' When `nail_qda_spaceprep()` is also used, applying the same
#' `expertise_mode` in both functions generally produces the most coherent
#' chain of interpretation.
#'
#' ## Prompt construction and generation
#'
#' Each retained dimension produces a separate prompt combining:
#'
#' - the study introduction;
#' - a statistical reading guide;
#' - the requested interpretation task;
#' - the percentage of inertia explained by the dimension;
#' - the sensory attributes associated with both sides of the dimension;
#' - the products positioned at both ends;
#' - optional deterministic or LLM-generated product descriptions;
#' - the requested final synthesis.
#'
#' By default, `generate = FALSE`, allowing the prompts and PCA results to be
#' inspected before any LLM call.
#'
#' When `generate = TRUE`, one independent request is sent for each retained
#' dimension.
#'
#' The generated response is an assisted interpretation of the PCA evidence.
#' It does not replace examination of the PCA maps, eigenvalues, contributions,
#' cosines, QDA model assumptions, panel performance, product-by-panelist
#' interactions, or other diagnostic information.
#'
#' The interpretation is descriptive and should not be presented as a causal
#' conclusion.
#'
#' @return
#' The returned object depends on `generate` and on whether at least one PCA
#' dimension reaches `min_inertia_pct`.
#'
#' When at least one dimension is retained and `generate = FALSE`, a named
#' list of character prompts is returned. The names are of the form `"Dim1"`,
#' `"Dim2"`, and so on.
#'
#' The following attributes are attached to the list:
#'
#' - `"qda_space"`: a list containing the complete PCA result, the adjusted
#'   mean table, the eigenvalue table, the retained axis indices,
#'   `scale.unit`, and `min_inertia_pct`;
#' - `"profile_summary"`: the deterministic product summaries used in the
#'   product-level evidence, when available;
#' - `"llm_profile_summaries"`: the normalized LLM product summaries used in
#'   the product-level evidence, when available.
#'
#' When at least one dimension is retained and `generate = TRUE`, a named list
#' is returned, with one generated result per retained dimension.
#'
#' Each generated result is a data frame returned by the selected LLM backend
#' and includes a `prompt` column containing the exact prompt sent to the
#' model.
#'
#' The same `"qda_space"`, `"profile_summary"`, and
#' `"llm_profile_summaries"` attributes are attached to the returned list.
#'
#' When no dimension reaches `min_inertia_pct`:
#'
#' - with `generate = FALSE`, an informative character string is returned and
#'   the complete product-space object is stored in its `"qda_space"`
#'   attribute;
#' - with `generate = TRUE`, no LLM is called and an empty list is returned.
#'
#' @seealso
#' [nail_qda()], [nail_qda_spaceprep()], [SensoMineR::decat()],
#' [FactoMineR::PCA()]
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # These examples use the sensochoc dataset from SensoMineR.
#' #
#' # The first examples construct and inspect the product space
#' # without calling a language model.
#' #
#' # The final examples use Ollama and may therefore take more than
#' # ten seconds to run.
#'
#' library(NaileR)
#' library(SensoMineR)
#'
#' data(chocolates, package = "SensoMineR")
#'
#'
#' ### Example 1: recommended workflow without an LLM ###
#'
#' # First characterize the sensory profile of each chocolate.
#' #
#' # Product is the first term in the model because it is the factor
#' # whose levels are characterized.
#' #
#' # Panelist is included to account for systematic differences
#' # between panelists.
#' qda_choc <- nail_qda(
#'   dataset = sensochoc,
#'   formul = "~Product+Panelist",
#'   firstvar = 5,
#'   lastvar = ncol(sensochoc),
#'   product_knowledge = "known",
#'   generate = FALSE
#' )
#'
#' # Build the PCA of the adjusted product means.
#' #
#' # scale.unit = TRUE is the default: each sensory attribute
#' # is standardized to unit variance before PCA.
#' #
#' # The deterministic product summaries produced by nail_qda()
#' # are extracted automatically. The user does not need to supply
#' # profile_summary.
#' #
#' # No LLM is called because generate = FALSE.
#' space_prompts <- nail_qda_space(
#'   x = qda_choc,
#'   ncp = 3,
#'   min_inertia_pct = 10,
#'   top_n_var = 5,
#'   top_n_products = 2,
#'   expertise_mode = "sensory",
#'   generate = FALSE
#' )
#'
#' # Display the retained dimensions.
#' names(space_prompts)
#'
#' # Display the prompt constructed for the first retained dimension.
#' cat(space_prompts[[1]])
#'
#'
#' ### Example 2: inspect the statistical product-space object ###
#'
#' # Recover the complete statistical object attached to the prompts.
#' space_choc <- attr(space_prompts, "qda_space")
#'
#' # Verify the scaling choice used in the PCA.
#' space_choc$scale.unit
#'
#' # Inspect the adjusted mean table used as input to the PCA.
#' space_choc$adjmean
#'
#' # Inspect the eigenvalues and percentages of inertia.
#' space_choc$eig
#'
#' # Identify the dimensions retained for automatic interpretation.
#' space_choc$retained_axes
#'
#' # Inspect the original FactoMineR PCA result.
#' names(space_choc$pca_result)
#'
#' # Plot the products.
#' plot.PCA(
#'   space_choc$pca_result,
#'   choix = "ind"
#' )
#'
#' # Plot the sensory attributes.
#' plot.PCA(
#'   space_choc$pca_result,
#'   choix = "var"
#' )
#'
#'
#' ### Example 3: use a raw decat result ###
#'
#' # A raw decat result can be supplied directly.
#' decat_choc <- attr(qda_choc, "decat_result")
#'
#' # The PCA can be constructed without manually supplying
#' # profile_summary.
#' #
#' # In this case, the products are located from their PCA coordinates,
#' # but the deterministic product summaries attached to qda_choc
#' # are not available to enrich their descriptions.
#' raw_space_prompts <- nail_qda_space(
#'   x = decat_choc,
#'   ncp = 3,
#'   scale.unit = TRUE,
#'   min_inertia_pct = 10,
#'   expertise_mode = "sensory",
#'   generate = FALSE
#' )
#'
#' cat(raw_space_prompts[[1]])
#'
#'
#' ### Example 4: compare scaling choices ###
#'
#' # PCA with unit-variance scaling, which is the default.
#' space_scaled <- nail_qda_space(
#'   x = qda_choc,
#'   ncp = 3,
#'   scale.unit = TRUE,
#'   min_inertia_pct = 0,
#'   generate = FALSE
#' )
#'
#' # PCA without unit-variance scaling.
#' space_unscaled <- nail_qda_space(
#'   x = qda_choc,
#'   ncp = 3,
#'   scale.unit = FALSE,
#'   min_inertia_pct = 0,
#'   generate = FALSE
#' )
#'
#' # Compare the percentages of inertia.
#' attr(space_scaled, "qda_space")$eig
#' attr(space_unscaled, "qda_space")$eig
#'
#'
#' ### Example 5: prepare optional LLM summaries for each product ###
#'
#' # Ollama must be running locally and the llama3 model
#' # must be installed.
#' #
#' # This preparation step is optional. It is not required to compute
#' # the PCA or to construct the product-space prompts.
#' #
#' # The same expertise mode is used in the preparation step
#' # and in the final product-space interpretation.
#' product_summaries <- nail_qda_spaceprep(
#'   dataset = sensochoc,
#'   formul = "~Product+Panelist",
#'   firstvar = 5,
#'   lastvar = ncol(sensochoc),
#'   product_knowledge = "known",
#'   expertise_mode = "sensory",
#'   provider = "ollama",
#'   model = "llama3",
#'   generate = TRUE
#' )
#'
#' # Inspect the parsed summary of the first product.
#' product_summaries[[1]]$parsed
#'
#' # Add the structured summaries to the product-space prompts
#' # without generating the final axis interpretations yet.
#' enriched_prompts <- nail_qda_space(
#'   x = qda_choc,
#'   llm_product_summaries = product_summaries,
#'   ncp = 3,
#'   min_inertia_pct = 10,
#'   expertise_mode = "sensory",
#'   generate = FALSE
#' )
#'
#' cat(enriched_prompts[[1]])
#'
#'
#' ### Example 6: generate the final interpretation of each dimension ###
#'
#' space_results <- nail_qda_space(
#'   x = qda_choc,
#'   llm_product_summaries = product_summaries,
#'   ncp = 3,
#'   scale.unit = TRUE,
#'   min_inertia_pct = 10,
#'   top_n_var = 5,
#'   top_n_products = 2,
#'   expertise_mode = "sensory",
#'   provider = "ollama",
#'   model = "llama3",
#'   generate = TRUE
#' )
#'
#' # Display the dimensions interpreted by the LLM.
#' names(space_results)
#'
#' # Display the generated interpretation of the first dimension.
#' cat(space_results[[1]]$response)
#'
#' # Display the exact prompt sent for the first dimension.
#' cat(space_results[[1]]$prompt)
#'
#'
#' ### Example 7: hybrid interpretation ###
#'
#' # Hybrid mode first interprets the sensory opposition,
#' # then considers a broader product-style contrast.
#' hybrid_prompts <- nail_qda_space(
#'   x = qda_choc,
#'   ncp = 3,
#'   min_inertia_pct = 10,
#'   expertise_mode = "hybrid",
#'   generate = FALSE
#' )
#'
#' cat(hybrid_prompts[[1]])
#' }
nail_qda_space <- function(x,
                           profile_summary = NULL,
                           llm_product_summaries = NULL,
                           ncp = 2,
                           scale.unit = TRUE,
                           min_inertia_pct = 10,
                           top_n_var = 5,
                           top_n_products = 2,
                           expertise_mode = c("sensory", "positioning", "hybrid"),
                           introduction = NULL,
                           request = NULL,
                           conclusion = NULL,
                           model = "llama3",
                           provider = c("ollama", "gemini"),
                           generate = FALSE,
                           ...) {
  expertise_mode <- match.arg(expertise_mode)

  provider <- match.arg(provider)

  validate_qda_space_inputs(
    ncp = ncp,
    scale.unit = scale.unit,
    min_inertia_pct = min_inertia_pct,
    top_n_var = top_n_var,
    top_n_products = top_n_products,
    generate = generate,
    expertise_mode = expertise_mode
  )

  extracted <- .extract_qda_space_inputs(x, profile_summary = profile_summary)
  decat_result <- extracted$decat_result
  profile_summary <- extracted$profile_summary
  llm_profile_summaries <- .extract_llm_profile_summaries(llm_product_summaries)

  space_obj <- .build_qda_space_object(
    decat_result = decat_result,
    ncp = ncp,
    scale.unit = scale.unit,
    min_inertia_pct = min_inertia_pct
  )

  if (is.null(introduction)) {
    introduction <- switch(
      expertise_mode,
      sensory = paste(
        "The results below describe the main dimensions of a product sensory space built from adjusted mean sensory profiles.",
        "Each dimension corresponds to one major sensory opposition between products in that space."
      ),
      positioning = paste(
        "The results below describe the main dimensions of a product space built from adjusted mean sensory profiles.",
        "Each dimension may reflect a broader contrast between product styles or product poles."
      ),
      hybrid = paste(
        "The results below describe the main dimensions of a product space built from adjusted mean sensory profiles.",
        "Each dimension first reflects a sensory opposition and may also suggest a broader contrast between product styles."
      )
    )
  }

  if (is.null(request)) {
    request <- build_request_qda_space(expertise_mode = expertise_mode)
  }

  if (is.null(conclusion)) {
    conclusion <- build_conclusion_qda_space(expertise_mode = expertise_mode)
  }

  guide <- build_guide_qda_space(
    min_inertia_pct = min_inertia_pct,
    expertise_mode = expertise_mode
  )
  introduction <- paste(introduction, guide, sep = "\n\n---\n\n")

  prompts <- tryCatch(
    {
      retained_axes <- space_obj$retained_axes

      if (length(retained_axes) == 0) {
        stop("No retained dimensions to interpret under the current inertia threshold.", call. = FALSE)
      }

      out <- lapply(retained_axes, function(ax) {
        eig <- space_obj$eig
        inertia_pct <- round(eig$percent[ax], 2)

        var_txt <- get_sentences_qda_axis(space_obj, axis = ax, top_n_var = top_n_var)
        prod_txt <- .build_axis_product_evidence(
          space_obj,
          axis = ax,
          profile_summary = profile_summary,
          llm_profile_summaries = llm_profile_summaries,
          top_n_products = top_n_products
        )

        data_txt <- paste(
          glue::glue("## Dimension {ax} ({inertia_pct}% of inertia)"),
          "",
          "### Variable-level evidence",
          "",
          var_txt,
          "",
          "### Product-level evidence",
          "",
          prod_txt,
          sep = "\n"
        )

        build_standard_prompt(
          introduction = introduction,
          request = request,
          data = data_txt,
          conclusion = conclusion
        )
      })

      names(out) <- paste0("Dim", retained_axes)
      out
    },
    error = function(e) {
      if (grepl("No retained dimensions", conditionMessage(e))) {
        "NAILER_NO_AXES_FOUND"
      } else {
        stop(e)
      }
    }
  )

  if (identical(prompts, "NAILER_NO_AXES_FOUND")) {
    no_axes_message <- paste0(
      "*No PCA dimension reached the minimum inertia threshold of ",
      min_inertia_pct,
      "% under the current settings.*"
    )

    if (generate) {
      message("Execution halted: No retained dimensions found. Nothing to generate.")
      return(list())
    }

    out <- no_axes_message
    attr(out, "qda_space") <- space_obj
    return(out)
  }

  if (!generate) {
    attr(prompts, "qda_space") <- space_obj
    attr(prompts, "profile_summary") <- profile_summary
    attr(prompts, "llm_profile_summaries") <- llm_profile_summaries
    return(prompts)
  }

  extra_args <- list(...)
  llm_api_options <- extra_args

  .call_llm <- function(prompt) {
    res_llm <- .call_llm_base(
      provider = provider,
      model = model,
      prompt = prompt,
      output = "df",
      llm_api_options = llm_api_options
    )
    res_llm$prompt <- prompt
    res_llm
  }

  out <- lapply(prompts, .call_llm)
  names(out) <- names(prompts)
  attr(out, "qda_space") <- space_obj
  attr(out, "profile_summary") <- profile_summary
  attr(out, "llm_profile_summaries") <- llm_profile_summaries
  out
}
